#!/usr/bin/env python
"""Generate a static project-level portfolio site."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from nerf_llm_scene_inspector.visualization.project_site import (  # noqa: E402
    DEFAULT_REPO_URL,
    build_project_site,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default="docs/index.html")
    parser.add_argument(
        "--run-index",
        default="",
        help="Optional run_index.json generated by scripts/index_runs.py or run_scene_pipeline.py.",
    )
    parser.add_argument("--repo-url", default=DEFAULT_REPO_URL)
    parser.add_argument("--max-runs", type=int, default=5)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    output = Path(args.output)
    if not output.is_absolute():
        output = ROOT / output
    run_index_path = Path(args.run_index) if args.run_index else None
    if run_index_path is not None and not run_index_path.is_absolute():
        run_index_path = ROOT / run_index_path

    site = build_project_site(
        output,
        repo_root=ROOT,
        run_index_path=run_index_path if run_index_path and run_index_path.exists() else None,
        repo_url=args.repo_url,
        max_runs=args.max_runs,
    )
    written = site.write_html(output)
    payload = {
        "output": str(written),
        "run_count": len(site.run_entries),
        "hero_image": site.hero_image,
        "repo_url": site.repo_url,
    }
    print(json.dumps(payload, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
